###
POST http://106.15.90.163:10086/api/create
Content-Type: application/json

{
  "title": "测试标题",
  "description": "这是一个测试",
  "start_time": "2025-12-12 00:00:00",
  "master": {
    "name": "测试主队",
    "logo": "url",
    "members": [
      {
        "name": "测试队员1",
        "position": "队长"
      },
      {
        "name": "测试队员2",
        "position": "队员"
      }
    ]
  },
  "guest": {
    "name": "测试客队",
    "logo": "url",
    "members": [
      {
        "name": "测试队员3",
        "position": "队长"
      },
      {
        "name": "测试队员4",
        "position": "队员"
      }
    ]
  }
}

###
POST http://106.15.90.163:10086//api/sync
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiJ9.eyJnYW1lSWQiOiI1N2I5ZWY4Nzc3MDA0YWZmYWM4NmYzN2VlMjIxMGIzYSIsInN1YiI6IjU3YjllZjg3NzcwMDRhZmZhYzg2ZjM3ZWUyMjEwYjNhIiwiaWF0IjoxNzY3ODQyODY0fQ.d5QUc1byc-JjwMGId6yNVINnqQo_RcSfKgbHWLndxC7FMNMgz8oh1I1EYQhgN9l_kubdtSFEJhxCNaFTn12f0Q",
  "team": "master",
  "members": [
    "测试队员1",
    "测试队员4"
  ],
  "action": "跳球",
  "score": 10,
  "time": "00:10:10"
}

###
GET http://106.15.90.163:10086/api/list

###
GET http://106.15.90.163:10086/api/view?uuid=57b9ef8777004affac86f37ee2210b3a